name: laycosWorld
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#cfcfcf'
    - '#afafaf'
    - '#414141'
    - '#747474'
  brandStrength: 0.8125
  lightness: 0.9326843174640089
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
