name: laycosWorld
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#662f3c'
    - '#e2cec2'
    - '#b29583'
    - '#7a5c50'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
